name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  provision_infraestructure:
    name: provision app infraestructure
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      working-directory: ./terraform
      run: terraform init
      env:
        GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
        # these TF_VAR_<var_name> can be accessed on terraform by var.<var name>
        # (e.g.: TF_VAR_project can be accessed on main.tf as var.project)
        TF_VAR_project: ${{ secrets.TF_VAR_project }} 
        TF_VAR_region: ${{ secrets.TF_VAR_region }}
        TF_VAR_zone: ${{ secrets.TF_VAR_zone }}

    - name: Terraform Format
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_project: ${{ secrets.TF_VAR_project }}
        TF_VAR_region: ${{ secrets.TF_VAR_region }}
        TF_VAR_zone: ${{ secrets.TF_VAR_zone }}