name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  provision_infraestructure:
    name: provision app infraestructure
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_ACTION_WORKING_DIR: 'terraform'
        TF_VAR_project: ${{ secrets.TF_VAR_project }}
        TF_VAR_region: ${{ secrets.TF_VAR_region }}
        TF_VAR_zone: ${{ secrets.TF_VAR_zone }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_ACTION_WORKING_DIR: 'terraform'
        TF_VAR_project: ${{ secrets.TF_VAR_project }}
        TF_VAR_region: ${{ secrets.TF_VAR_region }}
        TF_VAR_zone: ${{ secrets.TF_VAR_zone }}